name = "tidal"
version = "0.1.0"

description = "A type-safe, HTML-free UI component library for Lustre"
licences = ["Apache-2.0"]
repository = { type = "github", user = "p424p424", repo = "tidal" }
links = [{ title = "GitHub", href = "https://github.com/p424p424/tidal" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
